export GC_DBFQDN="127.0.0.1"
export GC_PORT="5432"
export GC_USER="gocron"
export GC_PASS="password1"
export GC_DBDATABASE="gocron"
export GC_INTERVAL="22"
export GC_PREFERSLACK="true"
export GC_SLACKHOOKURL="https://slack.com"
export GC_SLACKCHANNEL="test_chan"

